Repository kyma-project/docker-registry, pull requests merged in 2024-12, with the labels that each got.

#253 Bump base go image
  components/operator/Dockerfile
Labels: cla: yes, lgtm, size/XS

#256 Btp integration test cleanup
  .github/actions/setup-btp/action.yaml
  .github/workflows/_integration-tests.yaml
  .gitignore
  tests/btp/Makefile
  tests/btp/README.md
  tests/btp/hack/Makefile
  tests/btp/hack/get_btp_file_name.sh
  tests/btp/hack/registry-availibility-check.sh
  tests/btp/hack/set-tf-envs.sh
  tests/btp/tf/main.tf
  tests/btp/tf/variables.tf
Labels: cla: yes, lgtm, size/L

#258 Properly check main status before release
  .github/scripts/verify-actions-status.sh
Labels: cla: yes, size/XS
