Repository kyma-project/docker-registry, pull requests merged in 2024-09, with the labels that each got.

#164 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: cla: yes, lgtm, size/XS

#165 docs: Add mandatory sections to README.md
  README.md
Labels: cla: yes, lgtm, size/S

#160 Add btp integration tests workflow
  .github/actions/setup-btp/action.yaml
  .github/actions/setup-kyma/action.yaml
  .github/workflows/_btp-integration-tests.yaml
  .github/workflows/push.yaml
  tests/btp/hack/Makefile
  tests/btp/hack/bootstrap.sh
  tests/btp/hack/get_btp_file_name.sh
  tests/btp/hack/set-tf-envs.sh
Labels: cla: yes, lgtm, size/L, kind/feature

#169 Fix kubectl apply -f
  tests/btp/hack/Makefile
Labels: cla: yes, size/XS

#170 Rm tf destroy from btp integration test
  .github/workflows/_integration-tests.yaml
Labels: cla: yes, lgtm, size/S

#172 Automate Docker Registry image bumping during release
  .github/workflows/create-release.yaml
  config/operator/base/kustomization.yaml
  hack/replace_docker_registry_version.sh
Labels: cla: yes, size/S

#171 Use kyma tf module
  .github/workflows/_integration-tests.yaml
  tests/btp/README.md
  tests/btp/hack/Makefile
  tests/btp/tf/kyma.tf
  tests/btp/tf/main.tf
  tests/btp/tf/oidc.tf
  tests/btp/tf/provider-sm.tf
  tests/btp/tf/provider.tf
  tests/btp/tf/subaccount.tf
  tests/btp/tf/variables.tf
Labels: cla: yes, lgtm, size/L

#174 Unify linter config
  components/operator/.golangci.yaml
  components/operator/internal/state/fsm.go
  components/operator/internal/state/installed_status.go
Labels: cla: yes, size/M

#176 Revert "Unify linter config (#174)"
  components/operator/.golangci.yaml
  components/operator/internal/state/fsm.go
  components/operator/internal/state/installed_status.go
Labels: cla: yes, lgtm, size/M

#175 Use github SHA intead of run_id as a part of btp integration test name
  .github/workflows/_integration-tests.yaml
Labels: cla: yes, lgtm, size/XS

#177 Lint tests
  components/operator/.golangci.yaml
  components/operator/internal/state/installed_status.go
Labels: cla: yes, lgtm, size/M

#179 chmod +x replace_docker_registry_version.sh
  hack/replace_docker_registry_version.sh
Labels: cla: yes, lgtm, size/XS

#180 Fix release version upgrade
  config/operator/base/kustomization.yaml
  hack/replace_docker_registry_version.sh
Labels: cla: yes, lgtm, size/XS

#182 bump rc tag
  sec-scanners-config.yaml
Labels: cla: yes, lgtm, size/XS

#178 Specify target ref for pull_request_target workflows
  .github/actions/rebase/action.yaml
  .github/workflows/_build.yaml
  .github/workflows/_images-verify.yaml
  .github/workflows/_integration-tests.yaml
  .github/workflows/_unit-tests.yaml
  .github/workflows/lint.yaml
  .github/workflows/markdown.yaml
Labels: cla: yes, lgtm, size/M

#187 Bump base golang image
  components/operator/Dockerfile
Labels: cla: yes, lgtm, size/XS

#189 Fix labels
  config/operator/base/crd/kustomization.yaml
  config/operator/base/kustomization.yaml
Labels: cla: yes, lgtm, size/S

#188 Fix controller-gen target to correctly detect version
  hack/tools.mk
Labels: cla: yes, size/XS

#181 Cleanup linter excludes
  components/operator/.golangci.yaml
  components/operator/controllers/testhelper_test.go
  components/operator/internal/state/fsm.go
  components/operator/internal/state/fsm_test.go
Labels: cla: yes, size/M

#194 Run image-verify workflow on PRs to main only
  .github/workflows/_images-verify.yaml
Labels: cla: yes, size/XS, kind/chore, area/ci

#195 Cherry-Pick ci changes
  .github/actions/rebase/action.yaml
  .github/workflows/_build.yaml
  .github/workflows/_images-verify.yaml
  .github/workflows/_integration-tests.yaml
  .github/workflows/_unit-tests.yaml
  .github/workflows/lint.yaml
  .github/workflows/markdown.yaml
Labels: cla: yes, lgtm, size/M, kind/chore, area/ci

#196 Run image-verify workflow on PRs to main only v2
  .github/workflows/_images-verify.yaml
  .github/workflows/pull.yaml
Labels: cla: yes, lgtm, size/XS, kind/chore, area/ci

#190 Fix labels in deployment template (#189)
  config/operator/base/crd/kustomization.yaml
  config/operator/base/kustomization.yaml
Labels: cla: yes, lgtm, size/S

#198 Bump tf http provider
  tests/btp/tf/main.tf
Labels: cla: yes, lgtm, size/XS

#199 Bump tf http provider
  tests/btp/tf/main.tf
Labels: cla: yes, lgtm, size/XS

#200 Update the Docker Registry docs
  docs/user/00-20-configure-docker-registry.md
  docs/user/00-30-storage-configuration.md
  docs/user/technical-reference/resources/06-20-docker-registry-cr.md
  docs/user/tutorials/01-10-use-registry-internally.md
  docs/user/tutorials/01-20-expose-registry.md
Labels: documentation, cla: yes, do-not-merge/hold, size/M

#205 Bump helm dependency
  components/operator/internal/tracing/watcher.go
  go.mod
  go.sum
Labels: cla: yes, lgtm, size/L

#204 Diable gateway and host fields when enabled is false
  config/operator/base/ui-extensions/dockerregistry/form
Labels: cla: yes, size/XS, area/docker-registry, kind/feature

#206 Fix link in root Docker Registry repo
  README.md
Labels: cla: yes, lgtm, size/XS

#207 Error when the PVC can't be reached
  components/operator/internal/state/storage.go
  components/operator/internal/state/storage_test.go
Labels: cla: yes, size/M, area/docker-registry, kind/feature

#208 Add sidebar.md and fix the docs layout
  docs/user/00-20-configure-docker-registry.md
  docs/user/00-30-storage-configuration.md
  docs/user/_sidebar.md
  docs/user/resources/06-20-docker-registry-cr.md
  docs/user/resources/README.md
  docs/user/technical-reference/README.md
Labels: cla: yes, lgtm, size/S

#210 Display storage type under the `storage` formGroup widget
  config/operator/base/ui-extensions/dockerregistry/form
Labels: cla: yes, lgtm, size/M, area/docker-registry, kind/feature

#211 Fix broken links in Docker Registry
  README.md
  docs/user/00-30-storage-configuration.md
Labels: cla: yes, lgtm, size/XS

#212 Bump grpc dependency
  go.mod
  go.sum
Labels: cla: yes, size/S

#214 Fix sidebar in docker-registry
  docs/user/_sidebar.md
Labels: cla: yes, lgtm, size/XS
