Repository kyma-project/docker-registry, pull requests merged in 2024-11, with the labels that each got.

#235 Trigger btp integration test only by create-release workflow
  .github/workflows/_integration-tests.yaml
  .github/workflows/create-release.yaml
Labels: cla: yes, size/XS

#232 Cleanup kyma resources for faster kyma runtime cleanup
  .github/workflows/_integration-tests.yaml
  tests/btp/hack/Makefile
Labels: cla: yes, size/S

#236 Fix retrying for req avail checks
  tests/btp/hack/registry-availibility-check.sh
Labels: cla: yes, lgtm, size/M, area/ci

#237 Fix retrying for req avail checks
  tests/btp/hack/Makefile
  tests/btp/hack/registry-availibility-check.sh
Labels: cla: yes, lgtm, size/XS

#240 Bump Go dependencies
  go.mod
  go.sum
Labels: cla: yes, size/M

#241 Bump k8s version
  .github/actions/create-k3d-cluster/action.yaml
  components/operator/api/v1alpha1/dockerregistry_types.go
  config/operator/base/crd/bases/operator.kyma-project.io_dockerregistries.yaml
  config/operator/base/rbac/role.yaml
  hack/gardener.mk
  hack/tools.mk
Labels: cla: yes, size/L
