Repository kyma-project/docker-registry, pull requests merged in 2024-10, with the labels that each got.

#215 Set fixed lint action version
  .github/workflows/lint.yaml
Labels: cla: yes, lgtm, size/XS, kind/chore, area/ci

#217 Bump sap/btp provider to 1.7.0 and use fixed kyma module
  tests/btp/tf/main.tf
Labels: cla: yes, lgtm, size/XS

#218 normalize github script names
  .github/scripts/create-changelog.sh
  .github/scripts/create-draft-release.sh
  .github/scripts/publish-release.sh
  .github/workflows/create-release.yaml
Labels: cla: yes, size/XS

#219 Simplify release id for assets
  .github/scripts/release.sh
  .github/workflows/create-release.yaml
Labels: cla: yes, size/S

#220 Fix link checker version
  .github/workflows/markdown.yaml
Labels: cla: yes, lgtm, size/S
