Repository kyma-project/docker-registry, pull requests merged in 2024-08, with the labels that each got.

#137 Bump helm dependency
  go.mod
  go.sum
Labels: cla: yes, lgtm, size/L

#139 Add pvc name to status
  components/operator/api/v1alpha1/dockerregistry_types.go
  components/operator/internal/state/installed_status.go
  components/operator/internal/state/installed_status_test.go
  config/operator/base/crd/bases/operator.kyma-project.io_dockerregistries.yaml
Labels: cla: yes, lgtm, size/M

#143 Turn on lint job on all PRs
  .github/workflows/lint.yaml
Labels: cla: yes, lgtm, size/XS

#142 improve docs about exposure
  docs/user/tutorials/01-20-expose-registry.md
Labels: cla: yes, lgtm, size/S

#141 Add PVC docs
  docs/user/00-30-storage-configuration.md
  docs/user/technical-reference/resources/06-20-docker-registry-cr.md
Labels: cla: yes, lgtm, size/S

#150 Add busola extension
  config/operator/base/ui-extensions/dockerregistry/details
  config/operator/base/ui-extensions/dockerregistry/form
  config/operator/base/ui-extensions/dockerregistry/general
  config/operator/base/ui-extensions/dockerregistry/kustomization.yaml
  config/operator/base/ui-extensions/dockerregistry/list
  config/operator/base/ui-extensions/dockerregistry/translations
Labels: cla: yes, lgtm, size/L

#158 Get rid of the `hostPrefix` field
  components/operator/api/v1alpha1/dockerregistry_types.go
  components/operator/api/v1alpha1/zz_generated.deepcopy.go
  components/operator/internal/state/access_test.go
  components/operator/internal/state/utils.go
  config/operator/base/crd/bases/operator.kyma-project.io_dockerregistries.yaml
  config/operator/base/ui-extensions/dockerregistry/form
  config/operator/base/ui-extensions/dockerregistry/translations
  docs/user/technical-reference/resources/06-20-docker-registry-cr.md
  docs/user/tutorials/01-20-expose-registry.md
Labels: cla: yes, lgtm, area/docker-registry, kind/chore

#156 BTP integration test
  .gitignore
  tests/btp/README.md
  tests/btp/hack/Makefile
  tests/btp/hack/bootstrap.sh
  tests/btp/hack/registry-availibility-check.sh
  tests/btp/k8s-resources/dependencies/exposed-docker-registry-with-btp-storage.yaml
  tests/btp/k8s-resources/dependencies/object-store-binding.yaml
  tests/btp/k8s-resources/simple-app/apirule.yaml
  tests/btp/k8s-resources/simple-app/deployment.yaml
  tests/btp/k8s-resources/simple-app/service.yaml
  tests/btp/tf/kyma.tf
  tests/btp/tf/oidc.tf
  tests/btp/tf/provider-sm.tf
  tests/btp/tf/provider.tf
  tests/btp/tf/subaccount.tf
  tests/btp/tf/variables.tf
Labels: cla: yes, size/XL, lgtm

#161 Warn user when custom gateway is not available
  components/operator/internal/istio/istio.go
  components/operator/internal/registry/external_access.go
  components/operator/internal/registry/external_access_test.go
  components/operator/internal/state/access.go
  components/operator/internal/state/access_test.go
Labels: cla: yes, lgtm, size/M, area/docker-registry, kind/feature

#162 Add the gateway field to the status
  components/operator/api/v1alpha1/dockerregistry_types.go
  components/operator/api/v1alpha1/zz_generated.deepcopy.go
  components/operator/internal/state/installed_status.go
  components/operator/internal/state/installed_status_test.go
  config/operator/base/crd/bases/operator.kyma-project.io_dockerregistries.yaml
Labels: cla: yes, lgtm, size/M, area/docker-registry, kind/feature

#163 Document custom gateway usage
  docs/user/technical-reference/resources/06-20-docker-registry-cr.md
Labels: cla: yes, lgtm, size/M, area/docker-registry, kind/chore, area/documentation
