Repository kyma-project/docker-registry, pull requests merged in 2024-05, with the labels that each got.

#21 Add the `registry-init` component
  components/registry-init/Dockerfile
  components/registry-init/README.md
Labels: cla: yes, lgtm, size/XS

#16 operator crud tests
  .github/workflows/operator-verify.yaml
  components/operator/api/v1alpha1/dockerregistry_types.go
  config/operator/base/deployment/kustomization.yaml
  go.mod
  go.sum
  tests/operator/Makefile
  tests/operator/dockerregistry/create.go
  tests/operator/dockerregistry/delete.go
  tests/operator/dockerregistry/deployment/verify.go
  tests/operator/dockerregistry/update.go
  tests/operator/dockerregistry/verify.go
  tests/operator/logger/logger.go
  tests/operator/main.go
  tests/operator/namespace/create.go
  tests/operator/namespace/delete.go
  tests/operator/utils/client.go
  tests/operator/utils/retry.go
  tests/operator/utils/types.go
Labels: enhancement, cla: yes, size/XL, lgtm

#22 Use the `registry` image synced by the image-syncer
  config/docker-registry/charts/docker-registry/templates/deployment.yaml
  config/docker-registry/values.yaml
  sec-scanners-config.yaml
Labels: cla: yes, lgtm, size/S

#23 Turn off update-integration GA job because of absence of release
  .github/workflows/operator-verify.yaml
  components/operator/Makefile
Labels: enhancement, cla: yes, lgtm, size/M

#26 Create the `rebase` action
  .github/actions/rebase/action.yaml
  .github/workflows/markdown.yaml
  .github/workflows/operator-verify.yaml
Labels: cla: yes, lgtm, size/M, area/docker-registry, kind/chore

#28 Fix values paths after chart refactor
  .github/scripts/upgrade-sec-scanners-config.sh
Labels: cla: yes, lgtm, size/XS

#30 Cover case when the `main` branch exists
  .github/actions/rebase/action.yaml
Labels: kind/bug, cla: yes, lgtm, size/XS, area/docker-registry

#29 Base secret not found
  components/operator/internal/chart/uninstall.go
  components/operator/internal/controllers/kubernetes/configmap_service.go
  components/operator/internal/controllers/kubernetes/namespace_controller.go
  components/operator/internal/controllers/kubernetes/serviceaccount_service.go
  components/operator/internal/controllers/kubernetes/shared.go
  components/operator/main.go
Labels: enhancement, cla: yes, lgtm, size/L

#31 Fix bug when updating main
  .github/actions/rebase/action.yaml
Labels: kind/bug, cla: yes, lgtm, size/XS, area/docker-registry

#24 split verification test gh workflows
  .github/actions/collect-cluster-info/action.yaml
  .github/actions/create-k3d-cluster/action.yaml
  .github/actions/setup-go/action.yaml
  .github/workflows/create-release.yaml
  .github/workflows/images-verify.yaml
  .github/workflows/integration-tests-pull.yaml
  .github/workflows/integration-tests-push.yaml
  .github/workflows/lint.yaml
  .github/workflows/markdown.yaml
  .github/workflows/operator-verify.yaml
  .github/workflows/unit-tests.yaml
  .github/workflows/upgrade-tests.yaml
Labels: enhancement, cla: yes, lgtm, size/L

#36 Fix path to dockerregistry-operator.yaml from release
  components/operator/Makefile
Labels: enhancement, cla: yes, lgtm, area/docker-registry

#35 extract version of go to input in action setup-go
  .github/actions/setup-go/action.yaml
Labels: cla: yes, lgtm, size/XS, area/docker-registry

#42 enable upgrade-tests
  .github/workflows/upgrade-tests.yaml
Labels: cla: yes, lgtm, size/M, area/docker-registry

#40 Deprecate kyma provision gardener
  hack/gardener.mk
  hack/save_kubeconfig.sh
  hack/shoot_template.yaml
Labels: cla: yes, lgtm, size/M

#44 Don't hibernate Gardener cluster
  hack/shoot_template.yaml
Labels: cla: yes, lgtm, size/XS

#39 add documentation
  README.md
  docs/contributor/03-10-scripts-not-working.md
  docs/contributor/04-10-testing-strategy.md
  docs/user/00-20-configure-docker-registry.md
  docs/user/README.md
  docs/user/resources/06-20-docker-registry-cr.md
  docs/user/resources/README.md
  docs/user/technical-reference/04-20-internal-registry.md
  docs/user/technical-reference/README.md
  docs/user/tutorials/01-10-simple-usage.md
  docs/user/tutorials/README.md
Labels: documentation, cla: yes, lgtm, size/L, area/docker-registry
