Repository kyma-project/docker-registry, pull requests merged in 2024-07, with the labels that each got.

#77 Update documents with new field info about external access
  docs/user/resources/06-20-docker-registry-cr.md
Labels: cla: yes, lgtm, size/M, area/docker-registry, kind/chore, area/documentation

#78 Move status update
  components/operator/internal/state/access.go
  components/operator/internal/state/access_test.go
  components/operator/internal/state/apply.go
  components/operator/internal/state/apply_test.go
  components/operator/internal/state/configuration_status.go
  components/operator/internal/state/configuration_status_test.go
  components/operator/internal/state/initialize.go
  components/operator/internal/state/initialize_test.go
  components/operator/internal/state/installed_status.go
  components/operator/internal/state/installed_status_test.go
  components/operator/internal/state/state.go
  components/operator/internal/state/storage.go
  components/operator/internal/state/storage_test.go
  components/operator/internal/state/update_status.go
  components/operator/internal/state/utils.go
  components/operator/internal/state/verify.go
  components/operator/internal/state/verify_test.go
Labels: cla: yes, size/XL, lgtm, area/docker-registry, kind/feature

#81 Add GCS to supported storage options
  components/operator/api/v1alpha1/dockerregistry_types.go
  components/operator/api/v1alpha1/zz_generated.deepcopy.go
  components/operator/internal/chart/flags.go
  components/operator/internal/state/installed_status.go
  components/operator/internal/state/storage.go
  components/operator/internal/state/storage_test.go
  config/docker-registry/templates/deployment.yaml
  config/docker-registry/templates/secret.yaml
  config/docker-registry/values.yaml
  config/operator/base/crd/bases/operator.kyma-project.io_dockerregistries.yaml
  docs/user/resources/06-20-docker-registry-cr.md
  docs/user/technical-reference/04-30-storage-configuration.md
Labels: cla: yes, lgtm, size/L

#85 Document basic usage
  README.md
  docs/user/00-30-storage-configuration.md
  docs/user/technical-reference/04-20-internal-registry.md
  docs/user/technical-reference/resources/06-20-docker-registry-cr.md
  docs/user/technical-reference/resources/README.md
  docs/user/tutorials/01-20-expose-registry.md
Labels: documentation, enhancement, cla: yes, lgtm, size/M

#87 add external secret propagation
  components/operator/internal/controllers/kubernetes/namespace_controller.go
  components/operator/internal/controllers/kubernetes/secret_service.go
  components/operator/internal/controllers/kubernetes/shared.go
  components/operator/main.go
Labels: cla: yes, lgtm, size/M, area/docker-registry, kind/chore

#86 Add btp objectstorage support
  components/operator/api/v1alpha1/dockerregistry_types.go
  components/operator/api/v1alpha1/zz_generated.deepcopy.go
  components/operator/internal/state/installed_status.go
  components/operator/internal/state/storage.go
  components/operator/internal/state/storage_test.go
  components/operator/internal/state/utils.go
  config/operator/base/crd/bases/operator.kyma-project.io_dockerregistries.yaml
Labels: cla: yes, lgtm, size/L

#92 Add btp storage docs
  docs/user/00-30-storage-configuration.md
  docs/user/technical-reference/resources/06-20-docker-registry-cr.md
Labels: cla: yes, lgtm, size/S

#89 add builds using ga workflows
  .github/workflows/build-pull.yaml
  .github/workflows/build-push.yaml
Labels: cla: yes, lgtm, size/M, area/docker-registry, kind/chore

#93 fix job and variable names in gh workflow build
  .github/workflows/build-push-release.yaml
Labels: cla: yes, lgtm, size/XS, area/docker-registry, kind/chore, area/ci

#96 Use synced images in Dockerfiles
  components/operator/Dockerfile
  components/registry-init/Dockerfile
Labels: cla: yes, lgtm, size/XS, area/docker-registry, kind/chore

#94 Add promote to release channel action
  .github/workflows/promote-to-release-channel.yaml
  Makefile
Labels: cla: yes, lgtm, size/M

#102 Fix link to docker-registry-cr.md
  docs/user/00-30-storage-configuration.md
Labels: cla: yes, lgtm, size/XS

#103 Fix second link to docker-registry-cr.md
  docs/user/00-30-storage-configuration.md
Labels: cla: yes, lgtm, size/XS

#97 Disable Azure support for BTP
  components/operator/internal/state/storage.go
  components/operator/internal/state/storage_test.go
  docs/user/00-30-storage-configuration.md
Labels: cla: yes, lgtm, size/M

#105 Adjust create-release job removing prow checking
  .github/scripts/verify-docker-registry-jobs-status.sh
  .github/workflows/create-release.yaml
Labels: cla: yes, lgtm, size/M

#109 Fix release
  .github/workflows/build-push.yaml
  .github/workflows/build-release.yaml
Labels: cla: yes, lgtm, size/M

#110 Fix regular expression
  .github/workflows/build-release.yaml
Labels: cla: yes, lgtm, size/XS

#111 Fix build (release) name
  .github/workflows/build-release.yaml
Labels: cla: yes, lgtm, size/XS

#107 Add existing PVC support
  components/operator/api/v1alpha1/dockerregistry_types.go
  components/operator/api/v1alpha1/zz_generated.deepcopy.go
  components/operator/internal/chart/flags.go
  components/operator/internal/state/installed_status.go
  components/operator/internal/state/storage.go
  components/operator/internal/state/storage_test.go
  config/docker-registry/values.yaml
  config/operator/base/crd/bases/operator.kyma-project.io_dockerregistries.yaml
Labels: cla: yes, lgtm, size/L

#113 Rework release workflow
  .github/workflows/build-release.yaml
  .github/workflows/create-release.yaml
Labels: cla: yes, lgtm, area/ci

#115 Allow pushing tag to repo
  .github/workflows/create-release.yaml
Labels: cla: yes, lgtm, size/XS

#116 Add needs for publish release
  .github/workflows/create-release.yaml
Labels: cla: yes, lgtm, size/XS

#114 create main gh workflows for pull and push events
  .github/workflows/_build-pull.yaml
  .github/workflows/_build-push.yaml
  .github/workflows/_images-verify.yaml
  .github/workflows/_integration-tests-pull.yaml
  .github/workflows/_integration-tests-push.yaml
  .github/workflows/_unit-tests.yaml
  .github/workflows/_upgrade-tests.yaml
  .github/workflows/pull.yaml
  .github/workflows/push.yaml
Labels: cla: yes, lgtm, size/M, area/docker-registry, kind/chore, area/ci

#117 Run workflows once
  .github/workflows/_build-pull.yaml
  .github/workflows/_build-push.yaml
  .github/workflows/_images-verify.yaml
  .github/workflows/_integration-tests-pull.yaml
  .github/workflows/_integration-tests-push.yaml
  .github/workflows/_unit-tests.yaml
  .github/workflows/_upgrade-tests.yaml
  .github/workflows/pull.yaml
  .github/workflows/push.yaml
Labels: cla: yes, lgtm, size/M, area/docker-registry, kind/chore, area/ci

#118 Merge integration workflows
  .github/workflows/_integration-tests-pull.yaml
  .github/workflows/_integration-tests.yaml
  .github/workflows/pull.yaml
  .github/workflows/push.yaml
Labels: cla: yes, lgtm, size/M, kind/chore, area/ci

#119 Merge build files
  .github/workflows/_build-pull.yaml
  .github/workflows/_build.yaml
  .github/workflows/pull.yaml
  .github/workflows/push.yaml
Labels: cla: yes, lgtm, size/M, kind/chore, area/ci

#121 Reuse integrations in the release flow
  .github/workflows/_integration-tests.yaml
  .github/workflows/create-release.yaml
  .github/workflows/pull.yaml
  .github/workflows/push.yaml
Labels: cla: yes, lgtm, size/S, area/docker-registry, kind/chore, area/ci

#122 Bump rc tag to 0.1.0
  sec-scanners-config.yaml
Labels: cla: yes, lgtm, size/XS

#124 Fix pull detection
  .github/workflows/_build.yaml
  .github/workflows/_integration-tests.yaml
Labels: enhancement, cla: yes, lgtm, size/XS, area/ci

#123 Update testing strategy
  docs/contributor/04-10-testing-strategy.md
Labels: cla: yes, lgtm, size/S, kind/chore, area/documentation

#128 Pass secrets to called integration and upgrade workflows
  .github/workflows/create-release.yaml
  .github/workflows/pull.yaml
  .github/workflows/push.yaml
Labels: cla: yes, lgtm, size/XS, kind/chore, area/ci

#129 Cherry-pick last serverless changes in context of integration tests readability
  .github/workflows/_integration-tests.yaml
  hack/save_kubeconfig.sh
Labels: cla: yes, lgtm, size/S, kind/chore, area/ci

#130 Fix module-config & change dir to docker-registry
  .github/workflows/promote-to-release-channel.yaml
  module-config-template.yaml
Labels: cla: yes, lgtm, size/S

#131 Fix build (release) workflow call
  .github/workflows/create-release.yaml
Labels: cla: yes, lgtm, size/XS

#132 Fail workflow when provisioning is not succeed
  hack/save_kubeconfig.sh
Labels: cla: yes, lgtm, size/XS, area/ci, kind/missing-test

#133 Add missing images to dependabot
  .github/dependabot.yml
Labels: cla: yes, lgtm, size/S

#136 Bump registry image
  config/docker-registry/values.yaml
Labels: cla: yes, lgtm, size/XS

#138 Bump registry image in sec-config
  sec-scanners-config.yaml
Labels: cla: yes, lgtm, size/XS
