Repository kyma-project/docker-registry, pull requests merged in 2025-03, with the labels that each got.

#303 fix build job permissions
  .github/workflows/push.yaml
Labels: lgtm, size/XS

#313 Update codeowners
  CODEOWNERS
Labels: enhancement, area/ci

#314 Improve cli extension
  config/operator/base/cli-extensions/dockerregistry/kustomization.yaml
  config/operator/base/cli-extensions/dockerregistry/rootCommand
Labels: documentation, area/docker-registry
