Repository kyma-project/docker-registry, pull requests merged in 2025-01, with the labels that each got.

#266 Allow users to delete images
  components/operator/api/v1alpha1/dockerregistry_types.go
  components/operator/internal/chart/flags.go
  components/operator/internal/state/installed_status.go
  components/operator/internal/state/installed_status_test.go
  components/operator/internal/state/storage.go
  components/operator/internal/state/storage_test.go
  config/docker-registry/README.md
  config/docker-registry/values.yaml
  config/operator/base/crd/bases/operator.kyma-project.io_dockerregistries.yaml
  docs/user/resources/06-20-docker-registry-cr.md
  go.mod
Labels: cla: yes, lgtm, size/L, area/docker-registry, kind/feature

#267 Restart registry deploy on its configmap content change
  components/operator/internal/chart/flags.go
  components/operator/internal/state/storage_test.go
Labels: enhancement, cla: yes, size/S, area/docker-registry

#272 Document the `.spec.deleteEnabled` field
  docs/user/_sidebar.md
  docs/user/tutorials/01-10-use-registry-internally.md
  docs/user/tutorials/01-30-remove-image-manifest.md
Labels: documentation, cla: yes, lgtm, size/M, area/docker-registry

#274 Add a note about the consequences of registry reconfiguration
  docs/user/00-30-storage-configuration.md
Labels: enhancement, cla: yes, size/XS, area/docker-registry, area/documentation

#273 Cleanup Dockerregistry CR details view
  config/operator/base/ui-extensions/dockerregistry/details
  config/operator/base/ui-extensions/dockerregistry/kustomization.yaml
Labels: cla: yes, lgtm, size/M

#276 Add storage info to status widget in UI
  config/operator/base/ui-extensions/dockerregistry/details
  config/operator/base/ui-extensions/dockerregistry/form
  config/operator/base/ui-extensions/dockerregistry/translations
Labels: cla: yes, size/S
